/*
-- Query: select * from theme
LIMIT 0, 1000

-- Date: 2022-05-30 13:20
*/
INSERT INTO `` (`thid`,`code`) VALUES (1,'2019 상반기 신규상장');
INSERT INTO `` (`thid`,`code`) VALUES (2,'2019 하반기 신규상장');
INSERT INTO `` (`thid`,`code`) VALUES (3,'2020 상반기 신규상장');
INSERT INTO `` (`thid`,`code`) VALUES (4,'2020 하반기 신규상장');
INSERT INTO `` (`thid`,`code`) VALUES (5,'2021 상반기 신규상장');
INSERT INTO `` (`thid`,`code`) VALUES (6,'2021 하반기 신규상장');
INSERT INTO `` (`thid`,`code`) VALUES (7,'2022 상반기 신규상장');
INSERT INTO `` (`thid`,`code`) VALUES (8,'2차전지');
INSERT INTO `` (`thid`,`code`) VALUES (9,'2차전지(LFP/리튬인산철)');
INSERT INTO `` (`thid`,`code`) VALUES (10,'2차전지(생산)');
INSERT INTO `` (`thid`,`code`) VALUES (11,'2차전지(소재/부품)');
INSERT INTO `` (`thid`,`code`) VALUES (12,'2차전지(장비)');
INSERT INTO `` (`thid`,`code`) VALUES (13,'2차전지(전고체)');
INSERT INTO `` (`thid`,`code`) VALUES (14,'3D 낸드(NAND)');
INSERT INTO `` (`thid`,`code`) VALUES (15,'3D 프린터');
INSERT INTO `` (`thid`,`code`) VALUES (16,'4대강 복원');
INSERT INTO `` (`thid`,`code`) VALUES (17,'4차산업 수혜주');
INSERT INTO `` (`thid`,`code`) VALUES (18,'5G(5세대 이동통신)');
INSERT INTO `` (`thid`,`code`) VALUES (19,'CCTV＆DVR');
INSERT INTO `` (`thid`,`code`) VALUES (20,'DMZ 평화공원');
INSERT INTO `` (`thid`,`code`) VALUES (21,'GTX(수도권 광역급행철도)');
INSERT INTO `` (`thid`,`code`) VALUES (22,'IT 대표주');
INSERT INTO `` (`thid`,`code`) VALUES (23,'K-뉴딜지수');
INSERT INTO `` (`thid`,`code`) VALUES (24,'K-뉴딜지수(2차전지)');
INSERT INTO `` (`thid`,`code`) VALUES (25,'K-뉴딜지수(게임)');
INSERT INTO `` (`thid`,`code`) VALUES (26,'K-뉴딜지수(바이오)');
INSERT INTO `` (`thid`,`code`) VALUES (27,'K-뉴딜지수(인터넷)');
INSERT INTO `` (`thid`,`code`) VALUES (28,'LCD BLU제조');
INSERT INTO `` (`thid`,`code`) VALUES (29,'LCD 부품/소재');
INSERT INTO `` (`thid`,`code`) VALUES (30,'LCD장비');
INSERT INTO `` (`thid`,`code`) VALUES (31,'LED');
INSERT INTO `` (`thid`,`code`) VALUES (32,'LED장비');
INSERT INTO `` (`thid`,`code`) VALUES (33,'LNG(액화천연가스)');
INSERT INTO `` (`thid`,`code`) VALUES (34,'LPG(액화석유가스)');
INSERT INTO `` (`thid`,`code`) VALUES (35,'MLCC(적층세라믹콘덴서)');
INSERT INTO `` (`thid`,`code`) VALUES (36,'mRNA(메신저 리보핵산)');
INSERT INTO `` (`thid`,`code`) VALUES (37,'MVNO(가상이동통신망사업자)');
INSERT INTO `` (`thid`,`code`) VALUES (38,'NFT(대체불가토큰)');
INSERT INTO `` (`thid`,`code`) VALUES (39,'NI(네트워크통합)');
INSERT INTO `` (`thid`,`code`) VALUES (40,'OLED(유기 발광 다이오드)');
INSERT INTO `` (`thid`,`code`) VALUES (41,'PCB(FPCB 등)');
INSERT INTO `` (`thid`,`code`) VALUES (42,'RFID(NFC 등)');
INSERT INTO `` (`thid`,`code`) VALUES (43,'SI(시스템통합)');
INSERT INTO `` (`thid`,`code`) VALUES (44,'SNS(소셜네트워크서비스)');
INSERT INTO `` (`thid`,`code`) VALUES (45,'SSD');
INSERT INTO `` (`thid`,`code`) VALUES (46,'U-Healthcare(원격진료)');
INSERT INTO `` (`thid`,`code`) VALUES (47,'UAM(도심항공모빌리티)');
INSERT INTO `` (`thid`,`code`) VALUES (48,'가상현실(VR)');
INSERT INTO `` (`thid`,`code`) VALUES (49,'가상화폐(비트코인 등)');
INSERT INTO `` (`thid`,`code`) VALUES (50,'강관업체(Steel pipe)');
INSERT INTO `` (`thid`,`code`) VALUES (51,'갤럭시 부품주');
INSERT INTO `` (`thid`,`code`) VALUES (52,'건강기능식품');
INSERT INTO `` (`thid`,`code`) VALUES (53,'건설 대표주');
INSERT INTO `` (`thid`,`code`) VALUES (54,'건설 중소형');
INSERT INTO `` (`thid`,`code`) VALUES (55,'건설기계');
INSERT INTO `` (`thid`,`code`) VALUES (56,'게임');
INSERT INTO `` (`thid`,`code`) VALUES (57,'겨울');
INSERT INTO `` (`thid`,`code`) VALUES (58,'고령화 사회(노인복지)');
INSERT INTO `` (`thid`,`code`) VALUES (59,'골판지 제조');
INSERT INTO `` (`thid`,`code`) VALUES (60,'골프');
INSERT INTO `` (`thid`,`code`) VALUES (61,'공기청정기');
INSERT INTO `` (`thid`,`code`) VALUES (62,'공작기계');
INSERT INTO `` (`thid`,`code`) VALUES (63,'광고');
INSERT INTO `` (`thid`,`code`) VALUES (64,'교육/온라인 교육');
INSERT INTO `` (`thid`,`code`) VALUES (65,'구제역/광우병 수혜');
INSERT INTO `` (`thid`,`code`) VALUES (66,'구충제(펜벤다졸, 이버멕틴 등)');
INSERT INTO `` (`thid`,`code`) VALUES (67,'국내 상장 중국기업');
INSERT INTO `` (`thid`,`code`) VALUES (68,'그래핀');
INSERT INTO `` (`thid`,`code`) VALUES (69,'기업인수목적회사(SPAC)');
INSERT INTO `` (`thid`,`code`) VALUES (70,'남-북-러 가스관사업');
INSERT INTO `` (`thid`,`code`) VALUES (71,'남북경협');
INSERT INTO `` (`thid`,`code`) VALUES (72,'농업');
INSERT INTO `` (`thid`,`code`) VALUES (73,'니켈 관련주');
INSERT INTO `` (`thid`,`code`) VALUES (74,'도시가스');
INSERT INTO `` (`thid`,`code`) VALUES (75,'두나무 관련주');
INSERT INTO `` (`thid`,`code`) VALUES (76,'드론(Drone)');
INSERT INTO `` (`thid`,`code`) VALUES (77,'리모델링/인테리어');
INSERT INTO `` (`thid`,`code`) VALUES (78,'리비안(RIVIAN) 관련주');
INSERT INTO `` (`thid`,`code`) VALUES (79,'리츠(REITs)');
INSERT INTO `` (`thid`,`code`) VALUES (80,'마리화나(대마)');
INSERT INTO `` (`thid`,`code`) VALUES (81,'마스크');
INSERT INTO `` (`thid`,`code`) VALUES (82,'마이데이터');
INSERT INTO `` (`thid`,`code`) VALUES (83,'마이크로 LED');
INSERT INTO `` (`thid`,`code`) VALUES (84,'마이크로바이옴');
INSERT INTO `` (`thid`,`code`) VALUES (85,'마켓컬리 관련주');
INSERT INTO `` (`thid`,`code`) VALUES (86,'메르스 코로나 바이러스');
INSERT INTO `` (`thid`,`code`) VALUES (87,'메타버스(Metaverse)');
INSERT INTO `` (`thid`,`code`) VALUES (88,'면세점');
INSERT INTO `` (`thid`,`code`) VALUES (89,'면역항암제');
INSERT INTO `` (`thid`,`code`) VALUES (90,'모바일게임(스마트폰)');
INSERT INTO `` (`thid`,`code`) VALUES (91,'모바일솔루션(스마트폰)');
INSERT INTO `` (`thid`,`code`) VALUES (92,'모바일콘텐츠(스마트폰/태블릿PC)');
INSERT INTO `` (`thid`,`code`) VALUES (93,'무선충전기술');
INSERT INTO `` (`thid`,`code`) VALUES (94,'미디어(방송/신문)');
INSERT INTO `` (`thid`,`code`) VALUES (95,'미용기기');
INSERT INTO `` (`thid`,`code`) VALUES (96,'바이오시밀러(복제 바이오의약품)');
INSERT INTO `` (`thid`,`code`) VALUES (97,'바이오인식(생체인식)');
INSERT INTO `` (`thid`,`code`) VALUES (98,'반도체 대표주(생산)');
INSERT INTO `` (`thid`,`code`) VALUES (99,'반도체 장비');
INSERT INTO `` (`thid`,`code`) VALUES (100,'반도체 재료/부품');
INSERT INTO `` (`thid`,`code`) VALUES (101,'밥솥');
INSERT INTO `` (`thid`,`code`) VALUES (102,'방위산업/전쟁 및 테러');
INSERT INTO `` (`thid`,`code`) VALUES (103,'백신/진단시약/방역(신종플루, AI 등)');
INSERT INTO `` (`thid`,`code`) VALUES (104,'백신여권');
INSERT INTO `` (`thid`,`code`) VALUES (105,'백화점');
INSERT INTO `` (`thid`,`code`) VALUES (106,'보안주(물리)');
INSERT INTO `` (`thid`,`code`) VALUES (107,'보안주(정보)');
INSERT INTO `` (`thid`,`code`) VALUES (108,'보톡스(보툴리눔톡신)');
INSERT INTO `` (`thid`,`code`) VALUES (109,'북한 광물자원개발');
INSERT INTO `` (`thid`,`code`) VALUES (110,'블록체인');
INSERT INTO `` (`thid`,`code`) VALUES (111,'비료');
INSERT INTO `` (`thid`,`code`) VALUES (112,'비철금속');
INSERT INTO `` (`thid`,`code`) VALUES (113,'사료');
INSERT INTO `` (`thid`,`code`) VALUES (114,'사물인터넷');
INSERT INTO `` (`thid`,`code`) VALUES (115,'삼성페이');
INSERT INTO `` (`thid`,`code`) VALUES (116,'생명보험');
INSERT INTO `` (`thid`,`code`) VALUES (117,'석유화학');
INSERT INTO `` (`thid`,`code`) VALUES (118,'선박평형수 처리장치');
INSERT INTO `` (`thid`,`code`) VALUES (119,'셰일가스(Shale Gas)');
INSERT INTO `` (`thid`,`code`) VALUES (120,'소매유통');
INSERT INTO `` (`thid`,`code`) VALUES (121,'소모성자재구매대행(MRO)');
INSERT INTO `` (`thid`,`code`) VALUES (122,'손해보험');
INSERT INTO `` (`thid`,`code`) VALUES (123,'수산');
INSERT INTO `` (`thid`,`code`) VALUES (124,'수소차(연료전지/부품/충전소 등)');
INSERT INTO `` (`thid`,`code`) VALUES (125,'수자원(양적/질적 개선)');
INSERT INTO `` (`thid`,`code`) VALUES (126,'슈퍼박테리아');
INSERT INTO `` (`thid`,`code`) VALUES (127,'스마트그리드(지능형전력망)');
INSERT INTO `` (`thid`,`code`) VALUES (128,'스마트카(SMART CAR)');
INSERT INTO `` (`thid`,`code`) VALUES (129,'스마트팩토리(스마트공장)');
INSERT INTO `` (`thid`,`code`) VALUES (130,'스마트폰');
INSERT INTO `` (`thid`,`code`) VALUES (131,'스마트홈(홈네트워크)');
INSERT INTO `` (`thid`,`code`) VALUES (132,'스포츠행사 수혜(올림픽, 월드컵 등)');
INSERT INTO `` (`thid`,`code`) VALUES (133,'시멘트/레미콘');
INSERT INTO `` (`thid`,`code`) VALUES (134,'시스템반도체');
INSERT INTO `` (`thid`,`code`) VALUES (135,'아스콘(아스팔트 콘크리트)');
INSERT INTO `` (`thid`,`code`) VALUES (136,'아이폰');
INSERT INTO `` (`thid`,`code`) VALUES (137,'아프리카 돼지열병(ASF)');
INSERT INTO `` (`thid`,`code`) VALUES (138,'야놀자 관련주');
INSERT INTO `` (`thid`,`code`) VALUES (139,'엔젤산업');
INSERT INTO `` (`thid`,`code`) VALUES (140,'엔터테인먼트');
INSERT INTO `` (`thid`,`code`) VALUES (141,'여름');
INSERT INTO `` (`thid`,`code`) VALUES (142,'여행');
INSERT INTO `` (`thid`,`code`) VALUES (143,'영상콘텐츠');
INSERT INTO `` (`thid`,`code`) VALUES (144,'영화');
INSERT INTO `` (`thid`,`code`) VALUES (145,'온실가스(탄소배출권)');
INSERT INTO `` (`thid`,`code`) VALUES (146,'요소수 관련주');
INSERT INTO `` (`thid`,`code`) VALUES (147,'우주항공산업');
INSERT INTO `` (`thid`,`code`) VALUES (148,'원숭이두창');
INSERT INTO `` (`thid`,`code`) VALUES (149,'원자력발전');
INSERT INTO `` (`thid`,`code`) VALUES (150,'원자력발전소 해체');
INSERT INTO `` (`thid`,`code`) VALUES (151,'웹툰');
INSERT INTO `` (`thid`,`code`) VALUES (152,'유전자 치료제/분석');
INSERT INTO `` (`thid`,`code`) VALUES (153,'육계');
INSERT INTO `` (`thid`,`code`) VALUES (154,'은행');
INSERT INTO `` (`thid`,`code`) VALUES (155,'음성인식');
INSERT INTO `` (`thid`,`code`) VALUES (156,'음식료업종');
INSERT INTO `` (`thid`,`code`) VALUES (157,'음원/음반');
INSERT INTO `` (`thid`,`code`) VALUES (158,'의료기기');
INSERT INTO `` (`thid`,`code`) VALUES (159,'인터넷 대표주');
INSERT INTO `` (`thid`,`code`) VALUES (160,'인터넷은행');
INSERT INTO `` (`thid`,`code`) VALUES (161,'일자리(취업)');
INSERT INTO `` (`thid`,`code`) VALUES (162,'자동차 대표주');
INSERT INTO `` (`thid`,`code`) VALUES (163,'자동차부품');
INSERT INTO `` (`thid`,`code`) VALUES (164,'자원개발');
INSERT INTO `` (`thid`,`code`) VALUES (165,'자율주행차');
INSERT INTO `` (`thid`,`code`) VALUES (166,'자전거');
INSERT INTO `` (`thid`,`code`) VALUES (167,'재난/안전(지진 등)');
INSERT INTO `` (`thid`,`code`) VALUES (168,'재택근무/스마트워크');
INSERT INTO `` (`thid`,`code`) VALUES (169,'전기자전거');
INSERT INTO `` (`thid`,`code`) VALUES (170,'전기차');
INSERT INTO `` (`thid`,`code`) VALUES (171,'전기차(충전소/충전기)');
INSERT INTO `` (`thid`,`code`) VALUES (172,'전력설비');
INSERT INTO `` (`thid`,`code`) VALUES (173,'전력저장장치(ESS)');
INSERT INTO `` (`thid`,`code`) VALUES (174,'전선');
INSERT INTO `` (`thid`,`code`) VALUES (175,'전자결제(전자화폐)');
INSERT INTO `` (`thid`,`code`) VALUES (176,'전자파');
INSERT INTO `` (`thid`,`code`) VALUES (177,'정유');
INSERT INTO `` (`thid`,`code`) VALUES (178,'제4이동통신');
INSERT INTO `` (`thid`,`code`) VALUES (179,'제대혈');
INSERT INTO `` (`thid`,`code`) VALUES (180,'제습기');
INSERT INTO `` (`thid`,`code`) VALUES (181,'제약업체');
INSERT INTO `` (`thid`,`code`) VALUES (182,'제지');
INSERT INTO `` (`thid`,`code`) VALUES (183,'조림사업');
INSERT INTO `` (`thid`,`code`) VALUES (184,'조선');
INSERT INTO `` (`thid`,`code`) VALUES (185,'조선기자재');
INSERT INTO `` (`thid`,`code`) VALUES (186,'종합 물류');
INSERT INTO `` (`thid`,`code`) VALUES (187,'종합상사');
INSERT INTO `` (`thid`,`code`) VALUES (188,'주류업(주정, 에탄올 등)');
INSERT INTO `` (`thid`,`code`) VALUES (189,'줄기세포');
INSERT INTO `` (`thid`,`code`) VALUES (190,'증강현실(AR)');
INSERT INTO `` (`thid`,`code`) VALUES (191,'증권');
INSERT INTO `` (`thid`,`code`) VALUES (192,'지능형로봇/인공지능(AI)');
INSERT INTO `` (`thid`,`code`) VALUES (193,'지주사');
INSERT INTO `` (`thid`,`code`) VALUES (194,'차량용블랙박스');
INSERT INTO `` (`thid`,`code`) VALUES (195,'창투사');
INSERT INTO `` (`thid`,`code`) VALUES (196,'철강 주요종목');
INSERT INTO `` (`thid`,`code`) VALUES (197,'철강 중소형');
INSERT INTO `` (`thid`,`code`) VALUES (198,'철도');
INSERT INTO `` (`thid`,`code`) VALUES (199,'출산장려정책');
INSERT INTO `` (`thid`,`code`) VALUES (200,'치매');
INSERT INTO `` (`thid`,`code`) VALUES (201,'치아 치료(임플란트 등)');
INSERT INTO `` (`thid`,`code`) VALUES (202,'카메라모듈/부품');
INSERT INTO `` (`thid`,`code`) VALUES (203,'카지노');
INSERT INTO `` (`thid`,`code`) VALUES (204,'카카오뱅크 관련주');
INSERT INTO `` (`thid`,`code`) VALUES (205,'캐릭터상품');
INSERT INTO `` (`thid`,`code`) VALUES (206,'케이블TV SO/MSO');
INSERT INTO `` (`thid`,`code`) VALUES (207,'코로나19(나파모스타트)');
INSERT INTO `` (`thid`,`code`) VALUES (208,'코로나19(덱사메타손)');
INSERT INTO `` (`thid`,`code`) VALUES (209,'코로나19(렘데시비르)');
INSERT INTO `` (`thid`,`code`) VALUES (210,'코로나19(모더나)');
INSERT INTO `` (`thid`,`code`) VALUES (211,'코로나19(스푸트니크V)');
INSERT INTO `` (`thid`,`code`) VALUES (212,'코로나19(음압병실/음압구급차)');
INSERT INTO `` (`thid`,`code`) VALUES (213,'코로나19(진단/치료제/백신 개발 등)');
INSERT INTO `` (`thid`,`code`) VALUES (214,'코로나19(진단키트)');
INSERT INTO `` (`thid`,`code`) VALUES (215,'코로나19(치료제/백신 개발 등)');
INSERT INTO `` (`thid`,`code`) VALUES (216,'코로나19(카모스타트)');
INSERT INTO `` (`thid`,`code`) VALUES (217,'코로나19(혈장치료/혈장치료제)');
INSERT INTO `` (`thid`,`code`) VALUES (218,'코로나19(화이자)');
INSERT INTO `` (`thid`,`code`) VALUES (219,'콜드체인(저온 유통)');
INSERT INTO `` (`thid`,`code`) VALUES (220,'쿠팡 관련주');
INSERT INTO `` (`thid`,`code`) VALUES (221,'크래프톤 관련주');
INSERT INTO `` (`thid`,`code`) VALUES (222,'클라우드 컴퓨팅');
INSERT INTO `` (`thid`,`code`) VALUES (223,'키오스크(KIOSK)');
INSERT INTO `` (`thid`,`code`) VALUES (224,'타이어');
INSERT INTO `` (`thid`,`code`) VALUES (225,'탄소나노튜브(CNT)');
INSERT INTO `` (`thid`,`code`) VALUES (226,'탈모 치료 관련주');
INSERT INTO `` (`thid`,`code`) VALUES (227,'태블릿PC');
INSERT INTO `` (`thid`,`code`) VALUES (228,'태양광에너지');
INSERT INTO `` (`thid`,`code`) VALUES (229,'태풍 및 장마');
INSERT INTO `` (`thid`,`code`) VALUES (230,'터치패널(스마트폰/태블릿PC 등)');
INSERT INTO `` (`thid`,`code`) VALUES (231,'테마파크');
INSERT INTO `` (`thid`,`code`) VALUES (232,'토스 관련주');
INSERT INTO `` (`thid`,`code`) VALUES (233,'통신');
INSERT INTO `` (`thid`,`code`) VALUES (234,'통신장비');
INSERT INTO `` (`thid`,`code`) VALUES (235,'패션/의류');
INSERT INTO `` (`thid`,`code`) VALUES (236,'페인트');
INSERT INTO `` (`thid`,`code`) VALUES (237,'편의점');
INSERT INTO `` (`thid`,`code`) VALUES (238,'폐기물처리');
INSERT INTO `` (`thid`,`code`) VALUES (239,'폐배터리 관련주');
INSERT INTO `` (`thid`,`code`) VALUES (240,'폴더블폰');
INSERT INTO `` (`thid`,`code`) VALUES (241,'풍력에너지');
INSERT INTO `` (`thid`,`code`) VALUES (242,'플렉서블 디스플레이');
INSERT INTO `` (`thid`,`code`) VALUES (243,'핀테크(FinTech)');
INSERT INTO `` (`thid`,`code`) VALUES (244,'항공/저가 항공사(LCC)');
INSERT INTO `` (`thid`,`code`) VALUES (245,'항공기부품');
INSERT INTO `` (`thid`,`code`) VALUES (246,'해운');
INSERT INTO `` (`thid`,`code`) VALUES (247,'해저터널(지하화/지하도로 등)');
INSERT INTO `` (`thid`,`code`) VALUES (248,'핵융합에너지');
INSERT INTO `` (`thid`,`code`) VALUES (249,'홈쇼핑');
INSERT INTO `` (`thid`,`code`) VALUES (250,'화장품');
INSERT INTO `` (`thid`,`code`) VALUES (251,'화폐/금융자동화기기(디지털화폐 등)');
INSERT INTO `` (`thid`,`code`) VALUES (252,'화학섬유');
INSERT INTO `` (`thid`,`code`) VALUES (253,'환율하락 수혜');
INSERT INTO `` (`thid`,`code`) VALUES (254,'황사/미세먼지');
INSERT INTO `` (`thid`,`code`) VALUES (255,'휴대폰부품');
INSERT INTO `` (`thid`,`code`) VALUES (256,'희귀금속(희토류 등)');
INSERT INTO `` (`thid`,`code`) VALUES (257,'日 수출 규제(국산화 등)');
INSERT INTO `` (`thid`,`code`) VALUES (258,'日제품 불매운동(수혜)');
INSERT INTO `` (`thid`,`code`) VALUES (259,'2019 상반기 신규상장');
INSERT INTO `` (`thid`,`code`) VALUES (260,'2019 하반기 신규상장');
INSERT INTO `` (`thid`,`code`) VALUES (261,'2020 상반기 신규상장');
INSERT INTO `` (`thid`,`code`) VALUES (262,'2020 하반기 신규상장');
INSERT INTO `` (`thid`,`code`) VALUES (263,'2021 상반기 신규상장');
INSERT INTO `` (`thid`,`code`) VALUES (264,'2021 하반기 신규상장');
INSERT INTO `` (`thid`,`code`) VALUES (265,'2022 상반기 신규상장');
INSERT INTO `` (`thid`,`code`) VALUES (266,'2차전지');
INSERT INTO `` (`thid`,`code`) VALUES (267,'2차전지(LFP/리튬인산철)');
INSERT INTO `` (`thid`,`code`) VALUES (268,'2차전지(생산)');
INSERT INTO `` (`thid`,`code`) VALUES (269,'2차전지(소재/부품)');
INSERT INTO `` (`thid`,`code`) VALUES (270,'2차전지(장비)');
INSERT INTO `` (`thid`,`code`) VALUES (271,'2차전지(전고체)');
INSERT INTO `` (`thid`,`code`) VALUES (272,'3D 낸드(NAND)');
INSERT INTO `` (`thid`,`code`) VALUES (273,'3D 프린터');
INSERT INTO `` (`thid`,`code`) VALUES (274,'4대강 복원');
INSERT INTO `` (`thid`,`code`) VALUES (275,'4차산업 수혜주');
INSERT INTO `` (`thid`,`code`) VALUES (276,'5G(5세대 이동통신)');
INSERT INTO `` (`thid`,`code`) VALUES (277,'CCTV＆DVR');
INSERT INTO `` (`thid`,`code`) VALUES (278,'DMZ 평화공원');
INSERT INTO `` (`thid`,`code`) VALUES (279,'GTX(수도권 광역급행철도)');
INSERT INTO `` (`thid`,`code`) VALUES (280,'IT 대표주');
INSERT INTO `` (`thid`,`code`) VALUES (281,'K-뉴딜지수');
INSERT INTO `` (`thid`,`code`) VALUES (282,'K-뉴딜지수(2차전지)');
INSERT INTO `` (`thid`,`code`) VALUES (283,'K-뉴딜지수(게임)');
INSERT INTO `` (`thid`,`code`) VALUES (284,'K-뉴딜지수(바이오)');
INSERT INTO `` (`thid`,`code`) VALUES (285,'K-뉴딜지수(인터넷)');
INSERT INTO `` (`thid`,`code`) VALUES (286,'LCD BLU제조');
INSERT INTO `` (`thid`,`code`) VALUES (287,'LCD 부품/소재');
INSERT INTO `` (`thid`,`code`) VALUES (288,'LCD장비');
INSERT INTO `` (`thid`,`code`) VALUES (289,'LED');
INSERT INTO `` (`thid`,`code`) VALUES (290,'LED장비');
INSERT INTO `` (`thid`,`code`) VALUES (291,'LNG(액화천연가스)');
INSERT INTO `` (`thid`,`code`) VALUES (292,'LPG(액화석유가스)');
INSERT INTO `` (`thid`,`code`) VALUES (293,'MLCC(적층세라믹콘덴서)');
INSERT INTO `` (`thid`,`code`) VALUES (294,'mRNA(메신저 리보핵산)');
INSERT INTO `` (`thid`,`code`) VALUES (295,'MVNO(가상이동통신망사업자)');
INSERT INTO `` (`thid`,`code`) VALUES (296,'NFT(대체불가토큰)');
INSERT INTO `` (`thid`,`code`) VALUES (297,'NI(네트워크통합)');
INSERT INTO `` (`thid`,`code`) VALUES (298,'OLED(유기 발광 다이오드)');
INSERT INTO `` (`thid`,`code`) VALUES (299,'PCB(FPCB 등)');
INSERT INTO `` (`thid`,`code`) VALUES (300,'RFID(NFC 등)');
INSERT INTO `` (`thid`,`code`) VALUES (301,'SI(시스템통합)');
INSERT INTO `` (`thid`,`code`) VALUES (302,'SNS(소셜네트워크서비스)');
INSERT INTO `` (`thid`,`code`) VALUES (303,'SSD');
INSERT INTO `` (`thid`,`code`) VALUES (304,'U-Healthcare(원격진료)');
INSERT INTO `` (`thid`,`code`) VALUES (305,'UAM(도심항공모빌리티)');
INSERT INTO `` (`thid`,`code`) VALUES (306,'가상현실(VR)');
INSERT INTO `` (`thid`,`code`) VALUES (307,'가상화폐(비트코인 등)');
INSERT INTO `` (`thid`,`code`) VALUES (308,'강관업체(Steel pipe)');
INSERT INTO `` (`thid`,`code`) VALUES (309,'갤럭시 부품주');
INSERT INTO `` (`thid`,`code`) VALUES (310,'건강기능식품');
INSERT INTO `` (`thid`,`code`) VALUES (311,'건설 대표주');
INSERT INTO `` (`thid`,`code`) VALUES (312,'건설 중소형');
INSERT INTO `` (`thid`,`code`) VALUES (313,'건설기계');
INSERT INTO `` (`thid`,`code`) VALUES (314,'게임');
INSERT INTO `` (`thid`,`code`) VALUES (315,'겨울');
INSERT INTO `` (`thid`,`code`) VALUES (316,'고령화 사회(노인복지)');
INSERT INTO `` (`thid`,`code`) VALUES (317,'골판지 제조');
INSERT INTO `` (`thid`,`code`) VALUES (318,'골프');
INSERT INTO `` (`thid`,`code`) VALUES (319,'공기청정기');
INSERT INTO `` (`thid`,`code`) VALUES (320,'공작기계');
INSERT INTO `` (`thid`,`code`) VALUES (321,'광고');
INSERT INTO `` (`thid`,`code`) VALUES (322,'교육/온라인 교육');
INSERT INTO `` (`thid`,`code`) VALUES (323,'구제역/광우병 수혜');
INSERT INTO `` (`thid`,`code`) VALUES (324,'구충제(펜벤다졸, 이버멕틴 등)');
INSERT INTO `` (`thid`,`code`) VALUES (325,'국내 상장 중국기업');
INSERT INTO `` (`thid`,`code`) VALUES (326,'그래핀');
INSERT INTO `` (`thid`,`code`) VALUES (327,'기업인수목적회사(SPAC)');
INSERT INTO `` (`thid`,`code`) VALUES (328,'남-북-러 가스관사업');
INSERT INTO `` (`thid`,`code`) VALUES (329,'남북경협');
INSERT INTO `` (`thid`,`code`) VALUES (330,'농업');
INSERT INTO `` (`thid`,`code`) VALUES (331,'니켈 관련주');
INSERT INTO `` (`thid`,`code`) VALUES (332,'도시가스');
INSERT INTO `` (`thid`,`code`) VALUES (333,'두나무 관련주');
INSERT INTO `` (`thid`,`code`) VALUES (334,'드론(Drone)');
INSERT INTO `` (`thid`,`code`) VALUES (335,'리모델링/인테리어');
INSERT INTO `` (`thid`,`code`) VALUES (336,'리비안(RIVIAN) 관련주');
INSERT INTO `` (`thid`,`code`) VALUES (337,'리츠(REITs)');
INSERT INTO `` (`thid`,`code`) VALUES (338,'마리화나(대마)');
INSERT INTO `` (`thid`,`code`) VALUES (339,'마스크');
INSERT INTO `` (`thid`,`code`) VALUES (340,'마이데이터');
INSERT INTO `` (`thid`,`code`) VALUES (341,'마이크로 LED');
INSERT INTO `` (`thid`,`code`) VALUES (342,'마이크로바이옴');
INSERT INTO `` (`thid`,`code`) VALUES (343,'마켓컬리 관련주');
INSERT INTO `` (`thid`,`code`) VALUES (344,'메르스 코로나 바이러스');
INSERT INTO `` (`thid`,`code`) VALUES (345,'메타버스(Metaverse)');
INSERT INTO `` (`thid`,`code`) VALUES (346,'면세점');
INSERT INTO `` (`thid`,`code`) VALUES (347,'면역항암제');
INSERT INTO `` (`thid`,`code`) VALUES (348,'모바일게임(스마트폰)');
INSERT INTO `` (`thid`,`code`) VALUES (349,'모바일솔루션(스마트폰)');
INSERT INTO `` (`thid`,`code`) VALUES (350,'모바일콘텐츠(스마트폰/태블릿PC)');
INSERT INTO `` (`thid`,`code`) VALUES (351,'무선충전기술');
INSERT INTO `` (`thid`,`code`) VALUES (352,'미디어(방송/신문)');
INSERT INTO `` (`thid`,`code`) VALUES (353,'미용기기');
INSERT INTO `` (`thid`,`code`) VALUES (354,'바이오시밀러(복제 바이오의약품)');
INSERT INTO `` (`thid`,`code`) VALUES (355,'바이오인식(생체인식)');
INSERT INTO `` (`thid`,`code`) VALUES (356,'반도체 대표주(생산)');
INSERT INTO `` (`thid`,`code`) VALUES (357,'반도체 장비');
INSERT INTO `` (`thid`,`code`) VALUES (358,'반도체 재료/부품');
INSERT INTO `` (`thid`,`code`) VALUES (359,'밥솥');
INSERT INTO `` (`thid`,`code`) VALUES (360,'방위산업/전쟁 및 테러');
INSERT INTO `` (`thid`,`code`) VALUES (361,'백신/진단시약/방역(신종플루, AI 등)');
INSERT INTO `` (`thid`,`code`) VALUES (362,'백신여권');
INSERT INTO `` (`thid`,`code`) VALUES (363,'백화점');
INSERT INTO `` (`thid`,`code`) VALUES (364,'보안주(물리)');
INSERT INTO `` (`thid`,`code`) VALUES (365,'보안주(정보)');
INSERT INTO `` (`thid`,`code`) VALUES (366,'보톡스(보툴리눔톡신)');
INSERT INTO `` (`thid`,`code`) VALUES (367,'북한 광물자원개발');
INSERT INTO `` (`thid`,`code`) VALUES (368,'블록체인');
INSERT INTO `` (`thid`,`code`) VALUES (369,'비료');
INSERT INTO `` (`thid`,`code`) VALUES (370,'비철금속');
INSERT INTO `` (`thid`,`code`) VALUES (371,'사료');
INSERT INTO `` (`thid`,`code`) VALUES (372,'사물인터넷');
INSERT INTO `` (`thid`,`code`) VALUES (373,'삼성페이');
INSERT INTO `` (`thid`,`code`) VALUES (374,'생명보험');
INSERT INTO `` (`thid`,`code`) VALUES (375,'석유화학');
INSERT INTO `` (`thid`,`code`) VALUES (376,'선박평형수 처리장치');
INSERT INTO `` (`thid`,`code`) VALUES (377,'셰일가스(Shale Gas)');
INSERT INTO `` (`thid`,`code`) VALUES (378,'소매유통');
INSERT INTO `` (`thid`,`code`) VALUES (379,'소모성자재구매대행(MRO)');
INSERT INTO `` (`thid`,`code`) VALUES (380,'손해보험');
INSERT INTO `` (`thid`,`code`) VALUES (381,'수산');
INSERT INTO `` (`thid`,`code`) VALUES (382,'수소차(연료전지/부품/충전소 등)');
INSERT INTO `` (`thid`,`code`) VALUES (383,'수자원(양적/질적 개선)');
INSERT INTO `` (`thid`,`code`) VALUES (384,'슈퍼박테리아');
INSERT INTO `` (`thid`,`code`) VALUES (385,'스마트그리드(지능형전력망)');
INSERT INTO `` (`thid`,`code`) VALUES (386,'스마트카(SMART CAR)');
INSERT INTO `` (`thid`,`code`) VALUES (387,'스마트팩토리(스마트공장)');
INSERT INTO `` (`thid`,`code`) VALUES (388,'스마트폰');
INSERT INTO `` (`thid`,`code`) VALUES (389,'스마트홈(홈네트워크)');
INSERT INTO `` (`thid`,`code`) VALUES (390,'스포츠행사 수혜(올림픽, 월드컵 등)');
INSERT INTO `` (`thid`,`code`) VALUES (391,'시멘트/레미콘');
INSERT INTO `` (`thid`,`code`) VALUES (392,'시스템반도체');
INSERT INTO `` (`thid`,`code`) VALUES (393,'아스콘(아스팔트 콘크리트)');
INSERT INTO `` (`thid`,`code`) VALUES (394,'아이폰');
INSERT INTO `` (`thid`,`code`) VALUES (395,'아프리카 돼지열병(ASF)');
INSERT INTO `` (`thid`,`code`) VALUES (396,'야놀자 관련주');
INSERT INTO `` (`thid`,`code`) VALUES (397,'엔젤산업');
INSERT INTO `` (`thid`,`code`) VALUES (398,'엔터테인먼트');
INSERT INTO `` (`thid`,`code`) VALUES (399,'여름');
INSERT INTO `` (`thid`,`code`) VALUES (400,'여행');
INSERT INTO `` (`thid`,`code`) VALUES (401,'영상콘텐츠');
INSERT INTO `` (`thid`,`code`) VALUES (402,'영화');
INSERT INTO `` (`thid`,`code`) VALUES (403,'온실가스(탄소배출권)');
INSERT INTO `` (`thid`,`code`) VALUES (404,'요소수 관련주');
INSERT INTO `` (`thid`,`code`) VALUES (405,'우주항공산업');
INSERT INTO `` (`thid`,`code`) VALUES (406,'원숭이두창');
INSERT INTO `` (`thid`,`code`) VALUES (407,'원자력발전');
INSERT INTO `` (`thid`,`code`) VALUES (408,'원자력발전소 해체');
INSERT INTO `` (`thid`,`code`) VALUES (409,'웹툰');
INSERT INTO `` (`thid`,`code`) VALUES (410,'유전자 치료제/분석');
INSERT INTO `` (`thid`,`code`) VALUES (411,'육계');
INSERT INTO `` (`thid`,`code`) VALUES (412,'은행');
INSERT INTO `` (`thid`,`code`) VALUES (413,'음성인식');
INSERT INTO `` (`thid`,`code`) VALUES (414,'음식료업종');
INSERT INTO `` (`thid`,`code`) VALUES (415,'음원/음반');
INSERT INTO `` (`thid`,`code`) VALUES (416,'의료기기');
INSERT INTO `` (`thid`,`code`) VALUES (417,'인터넷 대표주');
INSERT INTO `` (`thid`,`code`) VALUES (418,'인터넷은행');
INSERT INTO `` (`thid`,`code`) VALUES (419,'일자리(취업)');
INSERT INTO `` (`thid`,`code`) VALUES (420,'자동차 대표주');
INSERT INTO `` (`thid`,`code`) VALUES (421,'자동차부품');
INSERT INTO `` (`thid`,`code`) VALUES (422,'자원개발');
INSERT INTO `` (`thid`,`code`) VALUES (423,'자율주행차');
INSERT INTO `` (`thid`,`code`) VALUES (424,'자전거');
INSERT INTO `` (`thid`,`code`) VALUES (425,'재난/안전(지진 등)');
INSERT INTO `` (`thid`,`code`) VALUES (426,'재택근무/스마트워크');
INSERT INTO `` (`thid`,`code`) VALUES (427,'전기자전거');
INSERT INTO `` (`thid`,`code`) VALUES (428,'전기차');
INSERT INTO `` (`thid`,`code`) VALUES (429,'전기차(충전소/충전기)');
INSERT INTO `` (`thid`,`code`) VALUES (430,'전력설비');
INSERT INTO `` (`thid`,`code`) VALUES (431,'전력저장장치(ESS)');
INSERT INTO `` (`thid`,`code`) VALUES (432,'전선');
INSERT INTO `` (`thid`,`code`) VALUES (433,'전자결제(전자화폐)');
INSERT INTO `` (`thid`,`code`) VALUES (434,'전자파');
INSERT INTO `` (`thid`,`code`) VALUES (435,'정유');
INSERT INTO `` (`thid`,`code`) VALUES (436,'제4이동통신');
INSERT INTO `` (`thid`,`code`) VALUES (437,'제대혈');
INSERT INTO `` (`thid`,`code`) VALUES (438,'제습기');
INSERT INTO `` (`thid`,`code`) VALUES (439,'제약업체');
INSERT INTO `` (`thid`,`code`) VALUES (440,'제지');
INSERT INTO `` (`thid`,`code`) VALUES (441,'조림사업');
INSERT INTO `` (`thid`,`code`) VALUES (442,'조선');
INSERT INTO `` (`thid`,`code`) VALUES (443,'조선기자재');
INSERT INTO `` (`thid`,`code`) VALUES (444,'종합 물류');
INSERT INTO `` (`thid`,`code`) VALUES (445,'종합상사');
INSERT INTO `` (`thid`,`code`) VALUES (446,'주류업(주정, 에탄올 등)');
INSERT INTO `` (`thid`,`code`) VALUES (447,'줄기세포');
INSERT INTO `` (`thid`,`code`) VALUES (448,'증강현실(AR)');
INSERT INTO `` (`thid`,`code`) VALUES (449,'증권');
INSERT INTO `` (`thid`,`code`) VALUES (450,'지능형로봇/인공지능(AI)');
INSERT INTO `` (`thid`,`code`) VALUES (451,'지주사');
INSERT INTO `` (`thid`,`code`) VALUES (452,'차량용블랙박스');
INSERT INTO `` (`thid`,`code`) VALUES (453,'창투사');
INSERT INTO `` (`thid`,`code`) VALUES (454,'철강 주요종목');
INSERT INTO `` (`thid`,`code`) VALUES (455,'철강 중소형');
INSERT INTO `` (`thid`,`code`) VALUES (456,'철도');
INSERT INTO `` (`thid`,`code`) VALUES (457,'출산장려정책');
INSERT INTO `` (`thid`,`code`) VALUES (458,'치매');
INSERT INTO `` (`thid`,`code`) VALUES (459,'치아 치료(임플란트 등)');
INSERT INTO `` (`thid`,`code`) VALUES (460,'카메라모듈/부품');
INSERT INTO `` (`thid`,`code`) VALUES (461,'카지노');
INSERT INTO `` (`thid`,`code`) VALUES (462,'카카오뱅크 관련주');
INSERT INTO `` (`thid`,`code`) VALUES (463,'캐릭터상품');
INSERT INTO `` (`thid`,`code`) VALUES (464,'케이블TV SO/MSO');
INSERT INTO `` (`thid`,`code`) VALUES (465,'코로나19(나파모스타트)');
INSERT INTO `` (`thid`,`code`) VALUES (466,'코로나19(덱사메타손)');
INSERT INTO `` (`thid`,`code`) VALUES (467,'코로나19(렘데시비르)');
INSERT INTO `` (`thid`,`code`) VALUES (468,'코로나19(모더나)');
INSERT INTO `` (`thid`,`code`) VALUES (469,'코로나19(스푸트니크V)');
INSERT INTO `` (`thid`,`code`) VALUES (470,'코로나19(음압병실/음압구급차)');
INSERT INTO `` (`thid`,`code`) VALUES (471,'코로나19(진단/치료제/백신 개발 등)');
INSERT INTO `` (`thid`,`code`) VALUES (472,'코로나19(진단키트)');
INSERT INTO `` (`thid`,`code`) VALUES (473,'코로나19(치료제/백신 개발 등)');
INSERT INTO `` (`thid`,`code`) VALUES (474,'코로나19(카모스타트)');
INSERT INTO `` (`thid`,`code`) VALUES (475,'코로나19(혈장치료/혈장치료제)');
INSERT INTO `` (`thid`,`code`) VALUES (476,'코로나19(화이자)');
INSERT INTO `` (`thid`,`code`) VALUES (477,'콜드체인(저온 유통)');
INSERT INTO `` (`thid`,`code`) VALUES (478,'쿠팡 관련주');
INSERT INTO `` (`thid`,`code`) VALUES (479,'크래프톤 관련주');
INSERT INTO `` (`thid`,`code`) VALUES (480,'클라우드 컴퓨팅');
INSERT INTO `` (`thid`,`code`) VALUES (481,'키오스크(KIOSK)');
INSERT INTO `` (`thid`,`code`) VALUES (482,'타이어');
INSERT INTO `` (`thid`,`code`) VALUES (483,'탄소나노튜브(CNT)');
INSERT INTO `` (`thid`,`code`) VALUES (484,'탈모 치료 관련주');
INSERT INTO `` (`thid`,`code`) VALUES (485,'태블릿PC');
INSERT INTO `` (`thid`,`code`) VALUES (486,'태양광에너지');
INSERT INTO `` (`thid`,`code`) VALUES (487,'태풍 및 장마');
INSERT INTO `` (`thid`,`code`) VALUES (488,'터치패널(스마트폰/태블릿PC 등)');
INSERT INTO `` (`thid`,`code`) VALUES (489,'테마파크');
INSERT INTO `` (`thid`,`code`) VALUES (490,'토스 관련주');
INSERT INTO `` (`thid`,`code`) VALUES (491,'통신');
INSERT INTO `` (`thid`,`code`) VALUES (492,'통신장비');
INSERT INTO `` (`thid`,`code`) VALUES (493,'패션/의류');
INSERT INTO `` (`thid`,`code`) VALUES (494,'페인트');
INSERT INTO `` (`thid`,`code`) VALUES (495,'편의점');
INSERT INTO `` (`thid`,`code`) VALUES (496,'폐기물처리');
INSERT INTO `` (`thid`,`code`) VALUES (497,'폐배터리 관련주');
INSERT INTO `` (`thid`,`code`) VALUES (498,'폴더블폰');
INSERT INTO `` (`thid`,`code`) VALUES (499,'풍력에너지');
INSERT INTO `` (`thid`,`code`) VALUES (500,'플렉서블 디스플레이');
INSERT INTO `` (`thid`,`code`) VALUES (501,'핀테크(FinTech)');
INSERT INTO `` (`thid`,`code`) VALUES (502,'항공/저가 항공사(LCC)');
INSERT INTO `` (`thid`,`code`) VALUES (503,'항공기부품');
INSERT INTO `` (`thid`,`code`) VALUES (504,'해운');
INSERT INTO `` (`thid`,`code`) VALUES (505,'해저터널(지하화/지하도로 등)');
INSERT INTO `` (`thid`,`code`) VALUES (506,'핵융합에너지');
INSERT INTO `` (`thid`,`code`) VALUES (507,'홈쇼핑');
INSERT INTO `` (`thid`,`code`) VALUES (508,'화장품');
INSERT INTO `` (`thid`,`code`) VALUES (509,'화폐/금융자동화기기(디지털화폐 등)');
INSERT INTO `` (`thid`,`code`) VALUES (510,'화학섬유');
INSERT INTO `` (`thid`,`code`) VALUES (511,'환율하락 수혜');
INSERT INTO `` (`thid`,`code`) VALUES (512,'황사/미세먼지');
INSERT INTO `` (`thid`,`code`) VALUES (513,'휴대폰부품');
INSERT INTO `` (`thid`,`code`) VALUES (514,'희귀금속(희토류 등)');
INSERT INTO `` (`thid`,`code`) VALUES (515,'日 수출 규제(국산화 등)');
INSERT INTO `` (`thid`,`code`) VALUES (516,'日제품 불매운동(수혜)');
